---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: solidarytech
  namespace: argocd
spec:
  description: Microsservicos da SolidaryTech monitorados pelo ArgoCD
  sourceRepos:
    - "https://github.com/marcelosilva-dev/tech-challenge-5-fiap"
  destinations:
    - namespace: solidarytech
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

---
# Shared resources: namespace + ingress
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solidarytech-shared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: solidarytech
  source:
    repoURL: https://github.com/marcelosilva-dev/tech-challenge-5-fiap
    targetRevision: main
    path: gitops
    directory:
      recurse: false # so arquivos da raiz de gitops/ (namespace + ingress)
  destination:
    server: https://kubernetes.default.svc
    namespace: solidarytech
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngo-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: solidarytech
  source:
    repoURL: https://github.com/marcelosilva-dev/tech-challenge-5-fiap
    targetRevision: main
    path: gitops/ngo-service
  destination:
    server: https://kubernetes.default.svc
    namespace: solidarytech
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: donation-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: solidarytech
  source:
    repoURL: https://github.com/marcelosilva-dev/tech-challenge-5-fiap
    targetRevision: main
    path: gitops/donation-service
  destination:
    server: https://kubernetes.default.svc
    namespace: solidarytech
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volunteer-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: solidarytech
  source:
    repoURL: https://github.com/marcelosilva-dev/tech-challenge-5-fiap
    targetRevision: main
    path: gitops/volunteer-service
  destination:
    server: https://kubernetes.default.svc
    namespace: solidarytech
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
